/* AUTH */
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_TOKEN_UPDATED = 'AUTH_TOKEN_UPDATED';
export const AUTH_STATUS_TOKEN_UPDATED = 'AUTH_STATUS_TOKEN_UPDATED';

/* MESSAGE */
export const MESSAGE_CHANGED = 'MESSAGE_CHANGED';
export const MESSAGE_CLOSED = 'MESSAGE_CLOSED';
export const MESSAGE_LOGOUT = 'MESSAGE_LOGOUT';

/* USER */
export const USER_LOADED = 'USER_LOADED';
export const USER_USERNAME_CHANGED = 'USER_USERNAME_CHANGED';
export const USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED';
export const USER_PHOTO_CHANGED = 'USER_PHOTO_CHANGED';
export const USER_LOGOUT = 'USER_LOGOUT';

/* APP */
export const APP_LOCATION_CHANGED = 'APP_LOCATION_CHANGED';
export const APP_CONNECTION_CHANGED = 'APP_CONNECTION_CHANGED';
export const APP_VISIBILITY_CHANGED = 'APP_VISIBILITY_CHANGED';
export const APP_ACTIVE_CHANGED = 'APP_ACTIVE_CHANGED';
export const APP_MENU_CHANGED = 'APP_MENU_CHANGED';
export const APP_THEME_CHANGED = 'APP_THEME_CHANGED';
export const APP_LOGOUT = 'APP_LOGOUT';
